CREATE TABLE "empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razao_social" varchar,
  "nome_fantasia" varchar,
  "cnpj" varchar UNIQUE,
  "inscricao_estadual" varchar,
  "regime_tributario" varchar,
  "ambiente_sefaz" varchar,
  "status" varchar,
  "data_criacao" datetime
);

CREATE TABLE "estabelecimento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "nome" varchar,
  "cnpj" varchar,
  "inscricao_estadual" varchar,
  "endereco" varchar,
  "cidade" varchar,
  "estado" varchar,
  "status" varchar
);

CREATE TABLE "perfil" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "descricao" varchar
);

CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "perfil_id" int NOT NULL,
  "nome" varchar,
  "email" varchar UNIQUE,
  "senha_hash" varchar,
  "ativo" boolean,
  "data_criacao" datetime
);

CREATE TABLE "produto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "descricao" varchar,
  "codigo_interno" varchar,
  "ncm" varchar,
  "cfop" varchar,
  "unidade" varchar,
  "preco" decimal,
  "ativo" boolean
);

CREATE TABLE "nfce" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "estabelecimento_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "numero" int,
  "serie" int,
  "chave_acesso" varchar UNIQUE,
  "data_emissao" datetime,
  "valor_total" decimal,
  "status" varchar,
  "protocolo_autorizacao" varchar
);

CREATE TABLE "item_nfce" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nfce_id" int NOT NULL,
  "produto_id" int NOT NULL,
  "quantidade" decimal,
  "valor_unitario" decimal,
  "valor_total" decimal,
  "ncm" varchar,
  "cfop" varchar
);

CREATE TABLE "pagamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nfce_id" int NOT NULL,
  "tipo" varchar,
  "valor" decimal
);

CREATE TABLE "consumidor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "cpf" varchar,
  "email" varchar
);

ALTER TABLE "estabelecimento" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("perfil_id") REFERENCES "perfil" ("id");

ALTER TABLE "produto" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id");

ALTER TABLE "nfce" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id");

ALTER TABLE "nfce" ADD FOREIGN KEY ("estabelecimento_id") REFERENCES "estabelecimento" ("id");

ALTER TABLE "nfce" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "item_nfce" ADD FOREIGN KEY ("nfce_id") REFERENCES "nfce" ("id");

ALTER TABLE "item_nfce" ADD FOREIGN KEY ("produto_id") REFERENCES "produto" ("id");

ALTER TABLE "pagamento" ADD FOREIGN KEY ("nfce_id") REFERENCES "nfce" ("id");
